Repository honeycombio/husky, pull requests merged in 2022-09, with the labels that each got.

#121 [feat] allow OTLP/http-json for metrics
  otlp/common.go
  otlp/common_test.go
  otlp/common_testhelpers.go
  otlp/errors.go
  otlp/logs_test.go
  otlp/traces_test.go
Labels: type: enhancement, version: bump minor

#122 [fix] unconsolidate header validation
  .circleci/config.yml
  .gitignore
  Makefile
  otlp/common.go
  otlp/common_test.go
Labels: type: bug, version: bump minor

#126 [feat] dataset targeting rules for OTel Logs
  otlp/common.go
  otlp/logs.go
  otlp/logs_test.go
Labels: type: enhancement, version: bump minor

#127 [fix] only classic teams must provide a dataset header when sending metrics
  otlp/common.go
  otlp/common_test.go
Labels: type: bug, version: no bump

#129 fix: avoid nil pointer
  otlp/common.go
  otlp/traces_test.go
Labels: type: bug, version: bump patch

#131 Prepare v0.16.1 release
  CHANGELOG.md
  version.go
Labels: type: maintenance, version: bump patch
