Repository honeycombio/husky, pull requests merged in 2022-05, with the labels that each got.

#74 Copy span attrs after resource attrs
  otlp/trace.go
Labels: type: bug, version: bump patch

#78 Convert OTLP span status.code type to integer earlier in the transform
  otlp/trace.go
  otlp/trace_test.go
Labels: type: bug, version: bump patch, status: oncall

#79 prepare 0.10.6 release
  CHANGELOG.md
  version.go
Labels: type: maintenance, status: oncall
