Repository honeycombio/husky, pull requests merged in 2022-02, with the labels that each got.

#35 feat!: environments & services support
  otlp/common.go
  otlp/common_test.go
  otlp/errors.go
  otlp/trace.go
  otlp/trace_test.go
Labels: type: enhancement, version: bump major

#38 feat!: include individual batch sizes
  otlp/common.go
  otlp/trace.go
  otlp/trace_test.go
Labels: version: bump minor

#39 maint: remove indent style from editorconfig
  .editorconfig
Labels: type: maintenance, version: no bump

#42 empty or missing service name should default to unknown_service
  otlp/errors.go
  otlp/trace.go
  otlp/trace_test.go
Labels: version: bump patch

#46 feat: truncate dataset name when service is unknown
  otlp/trace.go
  otlp/trace_test.go
Labels: type: enhancement, version: bump minor

#48 feat: update metrics header validation
  otlp/common.go
  otlp/common_test.go
Labels: type: enhancement, version: bump minor
