Repository honeycombio/husky, pull requests merged in 2022-11, with the labels that each got.

#146 OTLP size fix
  go.mod
  go.sum
  otlp/common.go
  otlp/common_test.go
  otlp/logs.go
  otlp/logs_test.go
Labels: type: bug, version: bump minor

#145 Fix kvlist and byte arrays marshalling
  go.mod
  go.sum
  otlp/common.go
  otlp/common_test.go
  otlp/logs.go
  otlp/logs_test.go
Labels: type: bug, type: enhancement, version: bump minor

#149 release: v0.18.0
  CHANGELOG.md
  version.go
Labels: type: maintenance, version: no bump, no-changelog

#151 ci: validate PR title
  .github/workflows/validate-pr-title.yml
Labels: type: maintenance, no-changelog, version: no-bump

#152 ci: update validate PR title workflow
  .github/workflows/validate-pr-title.yml
Labels: type: enhancement, no-changelog, version: no-bump
