Repository honeycombio/husky, pull requests merged in 2022-04, with the labels that each got.

#57 Update go to 1.18
  .circleci/config.yml
  go.mod
Labels: type: maintenance, version: no bump

#66 Update OTLP proto to v0.11.0
  go.mod
  go.sum
Labels: type: maintenance, version: bump patch

#69 Fix library.version spillover between spans in a single batch
  otlp/trace.go
  otlp/trace_test.go
Labels: type: bug, version: bump patch
