Repository honeycombio/husky, pull requests merged in 2022-03, with the labels that each got.

#51 Prepare v0.10.1 release
  CHANGELOG.md
  version.go
Labels: type: maintenance, version: bump patch

#52 feat: trim dataset when deriving from service.name
  otlp/trace.go
  otlp/trace_test.go
Labels: type: bug, version: bump patch

#53 Update publish github filters in CircleCI config
  .circleci/config.yml
Labels: type: maintenance, version: no bump

#58 Create dependabot.yml
  .github/dependabot.yml
Labels: type: maintenance, version: no bump
