Repository honeycombio/husky, pull requests merged in 2022-08, with the labels that each got.

#106 Replace usage of OTLP proto with internal copy
  go.mod
  go.sum
  internal/go.opentelemetry.io/proto/otlp/go.mod
  otlp/common.go
  otlp/common_test.go
  otlp/logs.go
  otlp/logs_test.go
  otlp/traces.go
  otlp/traces_test.go
  proto/otlp/collector/logs/v1/logs_service.pb.go
  proto/otlp/collector/logs/v1/logs_service.pb.gw.go
  proto/otlp/collector/metrics/v1/metrics_service.pb.go
  proto/otlp/collector/metrics/v1/metrics_service.pb.gw.go
  proto/otlp/collector/trace/v1/trace_config.pb.go
  proto/otlp/collector/trace/v1/trace_service.pb.go
  proto/otlp/collector/trace/v1/trace_service.pb.gw.go
  proto/otlp/common/v1/common.pb.go
  proto/otlp/logs/v1/logs.pb.go
  proto/otlp/metrics/v1/metrics.pb.go
  proto/otlp/resource/v1/resource.pb.go
  proto/otlp/trace/v1/trace.pb.go
Labels: type: enhancement

#110 Update OTLP proto to v0.19.0
  proto/otlp/collector/logs/v1/logs_service.pb.go
  proto/otlp/collector/logs/v1/logs_service_grpc.pb.go
  proto/otlp/collector/metrics/v1/metrics_service.pb.go
  proto/otlp/collector/metrics/v1/metrics_service_grpc.pb.go
  proto/otlp/collector/trace/v1/trace_config.pb.go
  proto/otlp/collector/trace/v1/trace_service.pb.go
  proto/otlp/collector/trace/v1/trace_service_grpc.pb.go
  proto/otlp/common/v1/common.pb.go
  proto/otlp/logs/v1/logs.pb.go
  proto/otlp/metrics/v1/metrics.pb.go
  proto/otlp/resource/v1/resource.pb.go
  proto/otlp/trace/v1/trace.pb.go
Labels: type: maintenance, version: bump minor

#108 Prepare release 0.14.0
  CHANGELOG.md
  version.go
Labels: type: maintenance, version: bump minor

#113 Don't duplicate scope attributes between scopes
  otlp/common.go
  otlp/logs.go
  otlp/logs_test.go
  otlp/traces.go
  otlp/traces_test.go
Labels: type: maintenance, version: bump patch

#112 Add support for translating otlp/json trace and log requests
  otlp/common.go
  otlp/common_test.go
  otlp/logs.go
  otlp/logs_test.go
  otlp/traces.go
  otlp/traces_test.go
Labels: type: enhancement, version: bump minor

#114 Prepare v0.15.0 release
  CHANGELOG.md
  version.go
Labels: type: maintenance, version: bump minor
