Repository honeycombio/husky, pull requests merged in 2023-03, with the labels that each got.

#179 fix: Proposed fix for JSON ingestion issue
  otlp/traces.go
Labels: type: bug

#182 fix: Fix bug in BytesToTraceID, add test for it.
  otlp/traces.go
  otlp/traces_test.go
Labels: type: bug, version: bump patch

#184 fix: ingest base64-encoded spanIDs from browsers
  otlp/traces.go
  otlp/traces_test.go
Labels: type: bug, merge at will
