Repository honeycombio/husky, pull requests merged in 2023-02, with the labels that each got.

#170 feat: Detect if scope is from instrumentation library
  otlp/common.go
  otlp/traces_test.go
Labels: type: enhancement

#171 rel: Prepare v0.20.0 release
  CHANGELOG.md
  version.go
Labels: type: maintenance, version: bump minor

#173 fix: update java library name prefix
  otlp/common.go
  otlp/traces_test.go
Labels: type: bug, version: bump patch

#174 fix: update dotnet library name prefix
  otlp/common.go
  otlp/traces_test.go
Labels: type: bug, version: bump patch

#172 fix: correct Ruby library/scope name prefix
  otlp/common.go
  otlp/traces_test.go
Labels: type: bug, version: bump patch
