Repository honeycombio/husky, pull requests merged in 2024-03, with the labels that each got.

#245 feat: add Classic Ingest Key support
  otlp/common.go
  otlp/common_test.go
Labels: type: enhancement, version: bump minor

#249 maint: group dependency updates
  .github/dependabot.yml
Labels: type: maintenance, version: no bump

#251 rel: prepare v0.26.0 release
  CHANGELOG.md
  version.go
Labels: type: maintenance, merge at will, no-changelog

#253 feat: Add tracing support
  otlp/common.go
  otlp/common_test.go
  otlp/logs.go
  otlp/logs_test.go
  otlp/traces.go
  otlp/traces_test.go
  telemetry.go
Labels: type: enhancement, version: bump minor, breaking-change

#254 rel: Prepare 0.27.0 release
  CHANGELOG.md
  version.go
Labels: type: maintenance, version: no bump
