Repository honeycombio/husky, pull requests merged in 2024-09, with the labels that each got.

#276 chore: Remove SizeBytes from Batch struct
  otlp/common.go
  otlp/logs.go
  otlp/logs_test.go
  otlp/traces.go
  otlp/traces_test.go
Labels: type: maintenance

#275 feat: add sample rate to logs if set
  otlp/common.go
  otlp/common_test.go
  otlp/logs.go
  otlp/logs_test.go
  otlp/traces.go
  otlp/traces_test.go
Labels: type: enhancement, version: bump minor

#278 feat: add PHP to list of telemetry libraries
  otlp/common.go
  otlp/traces_test.go
Labels: merge at will, version: bump minor
